#!/system/bin/sh
# Runs by the manager (Magisk/KernelSU/SukiSU) right before removing this module.
# Keep the user's config (config.json); remove the module's auto-generated by-products.
rm -f /data/system/permkeeper/baseline.json
rm -f /data/system/permkeeper/apps.json
rm -f /data/system/permkeeper/labels.json
rm -f /data/system/permkeeper/apply.json
rm -f /data/system/permkeeper_apply.json
rm -rf /data/system/permkeeper/icon
rm -rf /data/adb/modules/permkeeper/webroot/icon
